### ISSUE TITLE
Format of ENVI header

### ISSUE THREAD

**Issue by SeltaZheng** [EnSpec/HyTools-sandbox#4]
A different formatted ENVI header is generated by Vectornormalization.
Original ENVI header: 
wavelength = { 365.92981 , 375.59399 , 385.26254 , 394.93552 , 404.61288 , 414.29462 , 423.98077...
VectorNorm output ENVI header:
wavelength = [  365.92981   375.59399   385.26254   394.93552   404.61288   414.29462...

The above format is not recognized by ENVI.

**Comment by adamchlus** [comment]
Issue resolved.
